services:
  db:
    image: postgres:16-alpine
    container_name: taskdb-compose
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - taskdata:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: taskapp
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:dev@db:5432/tasks
    depends_on:
      - db

volumes:
  taskdata: